name: timeseries_sealevel
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - matplotlib
  - scikit-learn=1.3.0
  - jupyter
  - jupyterlab
  - statsmodels=0.14.0
  - scipy=1.10.1
  - arch-py
  - pymannkendall=1.4.3
  - pmdarima=2.0.3
